baseURL = "http://example.org/"
languageCode = "en-us"
title = "Valentin Dittmar"
theme = "PaperMod"

[params.profileMode]
enabled = true
title = "Valentin Dittmar"
subtitle = "Software Entwicker"
imageUrl = "me-square.jpg"
imageTitle = "Valentin Dittmar"
imageWidth = 240        
imageHeight = 240
