name: GitHub Pages deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  NODE_VERSION: lts/gallium
  NPM_VERSION: v7.10.0

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Hugo
        uses: lowply/build-hugo@v0.88.1

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_SECRET_DEPLOY }}
        with:
          source-directory: 'public/'
          destination-github-username: ${{ secrets.GH_USERNAME }}
          destination-repository-name: 'valentindi.github.io'
          user-email: ${{ secrets.GH_EMAIL }}
          target-branch: main
