name: GitHub Pages deploy
on:
  release:
    types: [published]
    
env:
  NODE_VERSION: lts/gallium

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Nodejs ${{  }}
      uses: actions/setup-node@2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: NPM install
      run: npm install -g --prefer-offline --no-audit npm@${{ env.NPM_VERSION }}
      shell: bash
      
    - name: NPM deploy
      run: npm run deploy
      shell: bash

    - name: Deploy to GitHub Pages
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/$valentindi.github.io.git
        npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
