name: GitHub Pages deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  NODE_VERSION: lts/gallium
  NPM_VERSION: v7.10.0

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: build
        run: hugo
        shell: bash

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          source-directory: 'public'
          destination-github-username: 'valentindi'
          destination-repository-name: 'valentindi.github.io'
          user-email: github-actions@valentindittmar.eu
          target-branch: main
