name: GitHub Pages deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  NODE_VERSION: lts/gallium
  NPM_VERSION: v7.10.0

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: install npm
        run: npm install -g --prefer-offline --no-audit npm@${{ env.NPM_VERSION }}
        shell: bash

      - name: install dependencies
        run: npm ci
        shell: bash

      - name: build
        run: npm run build
        shell: bash
        env:
          VITE_BUILD_DATE: ${{ steps.date.outputs.date }}
          VITE_BUILD_HASH: ${{ env.GITHUB_SHA }}

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${{secrets.GH_SECRET_DEPLOY}}@github.com/valentindi/valentindi.github.io.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
          touch .nojekyll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
